### ISSUE TITLE
Problem with session

### ISSUE THREAD

**Issue by LapinW** [seek-for-android/open-mobile-api-sample#1]
Hello
I download your project on my android phone. I have : 
Selected reader:"SIM - UICC"
service session is null

i don't understand why i got this exception. I seek on the web but i can't find a solution.
Can you help me ?

**Comment by marcobrador** [comment]
Please, use the mailing list for this kind of issues: https://groups.google.com/forum/#!forum/seek-for-android

**Comment by yangyonguo** [comment]
Hi, 
Please how can i get the dependency classes package org.simalliance.openmobileapi.*
